### ISSUE TITLE
HackFS Judging

### ISSUE THREAD

**Issue by DeveloperAlly** [ahsueh1996/Pensieve-#8]
Heya! 

Really cool project - would love to see if the dao voting model could be handled byLilypad/Bacalhau in future too.

Great job team!

**Comment by ahsueh1996** [comment]
@DeveloperAlly Thank you for viewing our project and your help connecting us to the right help over at Slack (my user name there was Kuei-Fang)! 

We didn't have time to explore Lilypad but I think I saw some really exciting things there regarding training AI models. 

One quick thought to throw back at you is the network whitelist. I find having to request a PR to be a little limiting for hackathons timeline, is there a way to streamline that in the future? I think Python is missing a lot of the Web3 packages (fingers crossed it's going to change in the future) so right now, if I were to integrate with other Web3 projects for the DAO voting idea you've mentioned, I would like to rely on the fundamental RESTful API calls without having to make PRs or my own cluster. What are your thoughts on that?

**Comment by DeveloperAlly** [comment]
The PR process won't change for whitelisting I imagine due  to security issues unfortunately, though I can certainly bring this feedback up and see if we can brainstorm a better process (maybe an ai pipeline could help ? ;)!

For the web3 packages, any chance you have common ones in mind you'd want included?

I'd love to make sure that happens

**Comment by ahsueh1996** [comment]
Hi @DeveloperAlly, sure! Thanks for your invitation to provide feedback. I'm chatting with my team to see if they can add to the list (I'm mostly an ML dev so I have limited experience with Web3 projects).

Below are few on my mind (I've included non web3 projects as well). I'm sorry if I mention domains that have already been whitelisted. I only met this issue when I tried to add a QR code functionality to turn Beryx data into a watermark for my preprocessing pipeline, so I didn't have time to check very closely what's available.

- IPFS
- Calling any smart contract on EVM
- OpenAI APIs
- Beryx (they were another sponsor at this hackathon, however they seem like they're just starting off.)
- Google APIs for connecting with Docs or Sheets
- wget calls to huggingface or github or other model repositories to download dynamically specified model files
- s3 or lamda
- other Bacalhau modules!

To just put everything into context, my philosophy for iterating on Bacalhau was motivated by minimizing the number of docker pushes I have to run. So being able to use API calls to resolve data or even subprocesses typically handled by downloading a new library, is attractive. Maybe when Docker fixes their problem, this niche need would fade.

**Comment by ehsueh** [comment]
Hi @DeveloperAlly, thanks for reaching out!

On the blockchain side, these integrations will be super useful:

* web3
* ethers
* the Graph - for indexed onchain data query (so our processing pipeline can get the onchain info directly without needing to trust the offchain callers to pass them in)
* ceramic composedb - e.g. right now our machine learning pipeline outputs segmentation labels and other image metadata that we'd love to query from our dApp. However, we currently have to save all that info to IPFS then have the receiver downstream to read from IPFS and write them to composedb (instead of just write directly to the database and get the dApp to query the database).
* chainlink - e.g. allow our Bacalhau machine learning processing results can be queried by the smart contract directly via oracles
* lit protocol - e.g. right now Bacalhau stores the processed data on IPFS without encrypting them. Having something like lit actions built in will allow results to be viewed only when access control conditions are met.
* zk proof - e.g. some way to prove in a zero-knowledge way that what whatever was ran in Bacalhau was actually the process agreed on and nothing was tampered with (some the critical steps downstreams can easily verify and consume the results)
